# Generated by Django 5.0.2 on 2024-03-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmiApp', '0002_rename_user_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
    ]
