# Generated by Django 5.0.2 on 2024-03-14 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmiApp', '0003_customuser_is_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('yoe', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('is_attempted', models.BooleanField(default=False)),
                ('questions', models.JSONField(null=True)),
                ('answers', models.JSONField(null=True)),
                ('expiry', models.DateTimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmiApp.customuser')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmiApp.interview')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmiApp.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmiApp.organisation'),
        ),
    ]
