# Generated by Django 5.0.2 on 2024-03-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmiApp', '0004_interview_interviewdetail_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
