# Generated by Django 5.0.2 on 2024-03-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmiApp', '0005_alter_organisation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdetail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='interviewdetail',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmiApp.customuser'),
        ),
    ]
