# Generated by Django 5.0.2 on 2024-03-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmiApp', '0006_interviewdetail_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
