# Generated by Django 5.0.2 on 2024-03-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmiApp', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewdetail',
            name='expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
